### ISSUE TITLE
Right dropdown is broken

### ISSUE THREAD

**Issue by sidevesh** [zhangyuannie/butter#16]
![image](https://github.com/zhangyuannie/butter/assets/17254413/39f381d8-b4eb-4dc7-b65d-1bcb83d151a6)
Not sure what that symbol means or what that dropdown is even supposed to be,
also the Preferences option is greyed out.

**Comment by zhangyuannie** [comment]
We try to get the label of the filesystem. In your case, it is not set. Fixed in #17 
Yeah preferences is just a placeholder.
