### ISSUE TITLE
Building package for Debian

### ISSUE THREAD

**Issue by iwconfig** [zhangyuannie/butter#27]
Running `ninja -C build` inside rust:bookworm docker container results in cargo complaining about not finding `glib-2.0.pc`.

```console
   Compiling glib-sys v0.18.1
The following warnings were emitted during compilation:

warning: glib-sys@0.18.1: 

error: failed to run custom build command for `glib-sys v0.18.1`

Caused by:
  process didn't exit successfully: `/tmp/butter/build/./target/release/build/glib-sys-6ef09edce329e343/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=GLIB_2.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=
  pkg-config exited with status code 1
  > PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags glib-2.0 glib-2.0 >= 2.77

  The system library `glib-2.0` required by crate `glib-sys` was not found.
  The file `glib-2.0.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `glib-2.0.pc`.

warning: build failed, waiting for other jobs to finish...
Traceback (most recent call last):
  File "/tmp/butter/scripts/cargo_build", line 40, in <module>
    ).check_returncode()
      ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['cargo', 'build', '--manifest-path', '../Cargo.toml', '--target-dir', './target', '--package', 'butter', '--release']' returned non-zero exit status 101.
[4/5] Generating po/ta/LC_MESSAGES/butter-ta.mo with a custom command
FAILED: src/butter src/butterd 
/tmp/butter/scripts/cargo_build --source-root .. --build-root . --package butter --output src/butter src/butterd
ninja: build stopped: subcommand failed.
```

`glib-2.0.pc` is available and setting PKG_CONFIG_PATH does not solve it.

```console
root@28bea536a7d5:/tmp/butter# find / -name glib-2.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/glib-2.0.pc
root@28bea536a7d5:/tmp/butter# PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/ ninja -C build
# [...]
  The system library `glib-2.0` required by crate `glib-sys` was not found.
  The file `glib-2.0.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  PKG_CONFIG_PATH contains the following:
      - /usr/lib/x86_64-linux-gnu/pkgconfig/

  HINT: you may need to install a package such as glib-2.0, glib-2.0-dev or glib-2.0-devel.
# [...]
```

`libglib2.0-0` and `libglib2.0-dev` is installed and I've also tried with the following installed:

	- `librust-pkg-config-dev`
	- `librust-glib-dev`
	- `librust-glib-sys-dev`
	- `librust-gtk4-dev`

but the result is the same.

With one of the latter three packages installed another error came up about not finding `gobject-2.0.pc` (gobject-sys@0.18.0) besides the one about `glib-2.0.pc`. I guess that is because I use the rust image and there's a conflict between the debian version and the version that comes with the image.

`build-essential` is installed.

🤷

### To Reproduce
1. docker run -it rust:bookworm bash
2. apt update && apt upgrade -y && apt install clang meson python3 libadwaita-1-dev libgtk-4-dev libbtrfsutil-dev policykit-1 systemd desktop-file-utils gettext
3. git clone https://github.com/zhangyuannie/butter.git && cd butter && meson --prefix=/usr build
4. ninja -C build # error
5. PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/ ninja -C build # error

### Expected Behavior
Compile the thing so I can install it, on Debian Bookworm.

### Environment
 - Distribution: Debian Bookworm (docker Rust image)
 - Desktop: None
 - Version: 36dc4f8

**Comment by zhangyuannie** [comment]
Looks like we require `glib-2.0 >= 2.77` (similarly for gobject) while the latest version on Debian 12 is [2.74](https://packages.debian.org/bookworm/libglib2.0-dev).

We generally move pretty closely with Gnome's update schedule. Latest butter requires gnome 45+ while Debian is on gnome 43 right now.

Unfortunately I don't think it will be easy to install butter on Debian anytime soon, until we find a way to package this is another way.

Feel free to reopen if you have other questions!
