### ISSUE TITLE
Crashes on snapshot list right-click

### ISSUE THREAD

**Issue by lnicola** [zhangyuannie/butter#29]
### To Reproduce
1. Have no (?) snapshots
2. Right-click the snapshot list
3. See error in the terminal:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"GtkColumnViewRowWidget"`,
 right: `"GtkListItemWidget"`', src/widgets/snapshot_view.rs:459:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected Behavior
Dunno, but no crash.

### Environment
 - Distribution: Fedora 40
 - Desktop: GNOME 46.3
 - Version: 1.0-1.fc38

**Comment by lnicola** [comment]
Probably fixed in https://github.com/zhangyuannie/butter/commit/36dc4f8a084f12a44324044d9bb3e9ea99348b17, might be nice to put up a new release.

**Comment by lnicola** [comment]
Well, I tried to build it from source, but...

```
thread 'main' panicked at src/ui/store.rs:104:70:
called `Result::unwrap()` on an `Err` value: MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.ServiceUnknown")))), Some("The name is not activatable"), Msg { type: Error, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 2, body: Signature("s") })
```

**Comment by zhangyuannie** [comment]
Yeah, my laziness is delaying the release.

In the meantime, you can use the git branch of copr:
https://copr.fedorainfracloud.org/coprs/zhangyuannie/butter-git
