### ISSUE TITLE
btrfs-grub integration

### ISSUE THREAD

**Issue by iconoclasthero** [zhangyuannie/butter#31]
I use GNOME on Rhino 2024.2.

I saw your https://www.reddit.com/r/Fedora/comments/wuotk0/butter_yet_another_btrfs_snapshot_manager_and/ post.

I want a btrfs manager that 
- is agnostic to the filesystem/subvolume layout/hierarchy
- is integrated with grub-btrfs so I can select snaps at boot.
- will take snaps automatically so that it actually gets done.

Combining butter and buttermanger would give me a GTK4/GNOME app that's agnostic to subvolume hierarchy and is integrated with grub-btrfs to select root images at boot.  (I do not expect that grub-btrfs is going to manage other things besides what is mounted at /, but if it could do more than that, so much the better.)

Please consider integrating some amount of grub-btrfs integration at least to the level of being able to select from a menu of root snapshots.

**Comment by zhangyuannie** [comment]
Me too my friend

**Comment by zhangyuannie** [comment]
Actually, upon closer look, per my understanding, grub-btrfs should technically already work with Butter.

Given:
> grub-btrfs supports manual snapshots [...]

And snapshots created by Butter are not much different from manually created one. I don't see why it would be different? Given Butter is layout agnostic, I'm not sure if anything can/should be done on Butter side.

Closing for now, feel free to reopen
